# first, we print the list of students
puts "The students of my cohort at Makers Academy"
puts "-------------------------------------------"
puts "Giacomo Patella"
puts "Nisar Tahir"
puts "Michael Fisher"
puts "Peter Kristo"
puts "Bruce Steedman"
puts "Asta Bevainyte"
puts "Hannah Knights"
puts "Simon Woolf"
puts "Ken Scott"
puts "Gianni Guitteaud"
puts "Anath Abensour"
puts "Erica Salvaneschi"
puts "Chris Hill"
puts "Nicky Keszler"
puts "Georgi Georgiev"
puts "Jean-Baptiste Blanc"
puts "Lara young"
puts "Kumy Veleppillai"
puts "James Graham"
puts "Tom Groombridge"
# finally, we print the total
print "Overall, we have "
# it's imprtnat that print () doesn't add new line characters
print 20
puts " great students"
